#!/bin/bash --
#
# This script installs extension overriding the whole extension directory
# in ~/.local/share/gnome-shell/extensions/.
#
# Note: if there is an error during execution of the script,
#       consult readme.MD for further details.
#
# Copyright (c) 2012-2014 Vadim@dbFin <vadim@dbfin.com>
# This file is distributed under the same license as dbFin YAWL GNOME Shell Extensions.
#

function ok() { echo -e "\e[32m$1\e[0m"; exit 0; }
function error() { echo -e "Error \e[31m$1\e[0m at step $2"; exit $2; }

[ $# -gt 0 ] && [ -f "./$1/autogen.sh" ] || error "usage: $BASH_SOURCE extension_name" 1
cd "./$1/"

echo 'Running autogen and make zip-file...'
make distclean 2>/dev/null
[ ! -d ./zip/ ] || rm -rf ./zip/
./autogen.sh --prefix="$HOME/.local/" && make && make zip-file && make distclean
[ -d ./zip/ ] && [ -f "./zip/$1@dbfin.com.shell-extension.zip" ] || error 'autogen or make did not finish successfully' 2

echo "Copying extension $1..."
d="$HOME/.local/share/gnome-shell/extensions/$1@dbfin.com/"
[ ! -d "$d" ] || rm -rf "$d"
mkdir -p "$d" || error "cannot create $d" 3
unzip -q "./zip/$1@dbfin.com.shell-extension.zip" -d "$d" || error "cannot unzip made extension to $d"

ok 'Everything seems OK.'
