#!/bin/bash --

git update-index -q --refresh || { echo 'Not a git repository.'; exit 1; }
git diff-index --quiet --cached HEAD \
    && git diff-index --quiet HEAD \
    && test -z "$( git ls-files --other --exclude-standard --directory . 2>&1 )" \
    || { echo 'The git repository is not clean.'; exit 1; }

read -p 'Short name: ' name
[[ "$name" =~ \  ]] && { echo 'Short name should not contain spaces.'; exit 1; }
[ -d ./$name/ ] && { echo "Folder $name already exists."; exit 1; }
[ -f ./images/$name.png ] || { echo "Icon images/$name.png not found."; exit 1; }

read -p 'Long name: ' ExtensionName

Name="${name^}"

read -p "This will install $ExtensionName into $name, proceed (y/n)? " yn
[[ "$yn" =~ ^[yY]$ ]] || exit 0

cp -r ./template/ ./$name/ && cd ./$name/ && {

mv src/dbfinmain.js src/dbfin$name.js
mv src/org.gnome.shell.extensions.dbfin.main.gschema.xml.in src/org.gnome.shell.extensions.dbfin.$name.gschema.xml.in
cp ../images/$name.png src/icon.png
find . -type f -print0 | xargs -0 sed -i -e "s|#%#name|$name|g"
find . -type f -print0 | xargs -0 sed -i -e "s|#%#Name|$Name|g"
find . -type f -print0 | xargs -0 sed -i -e "s|#%#ExtensionName|$ExtensionName|g"

cd .. \
    && git checkout -b $name \
    && git rm -r template/ \
    && git rm new-extension \
    && git add -u . \
    && git add -A $name/ \
    && git commit -m "New extension $ExtensionName."

}
